
mongo:
  image: mongo:3.2.12 
  volumes_from:
    - mongo-data
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false"

mongo-data:
  image: mongo:3.2.12
  volumes:
    - ./.db/:/data/db
  command: "--break-mongo" # break mongod command and use it as data-volume-container
